In [30]:
import numpy as np
import pandas as pd
import plotly.express as px
import warnings
warnings.filterwarnings("ignore")

In [31]:
import plotly.figure_factory as ff

In [32]:
df = pd.read_csv(r"A:\Machine Learning\Datasets\heart.csv")

In [33]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

#### EDA (Exploratory Data Analysis)

In [34]:
df.shape

(918, 12)

In [35]:
df.columns

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='object')

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [37]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [38]:
df.describe(include= "object")

        Sex ChestPainType RestingECG ExerciseAngina ST_Slope
count   918           918        918            918      918
unique    2             4          3              2        3
top       M           ASY     Normal              N     Flat
freq    725           496        552            547      460

In [39]:
df.duplicated().sum()

np.int64(0)

In [40]:
df["HeartDisease"].value_counts()

HeartDisease
1    508
0    410
Name: count, dtype: int64

In [41]:
fig = px.histogram(df, x= "HeartDisease", title= "Heart Diesease")
fig.show()

In [42]:
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [43]:
num_columns = [df["Age"], df["Cholesterol"], df["RestingBP"], df["FastingBS"], df["MaxHR"], df["Oldpeak"]]  
labels = ["Age", "Cholesterol", "RestingBP", "FastingBS", "MaxHR", "Oldpeak"]
fig = ff.create_distplot(num_columns, show_rug= False, show_hist= True, group_labels= labels)

fig.show()

In [44]:
df["Cholesterol"].value_counts()

Cholesterol
0      172
254     11
220     10
223     10
204      9
      ...
353      1
278      1
157      1
176      1
131      1
Name: count, Length: 222, dtype: int64

In [45]:
ch_mean = df.loc[df["Cholesterol"] != 0, "Cholesterol"].mean()

In [46]:
df["Cholesterol"] = df["Cholesterol"].replace(0, ch_mean)
df["Cholesterol"] = df["Cholesterol"].round()

bp_mean = df.loc[df["RestingBP"] != 0, "RestingBP"].mean()
df["RestingBP"] = df["RestingBP"].replace(0, bp_mean)
df["RestingBP"] = df["RestingBP"].round()

In [47]:
fig = px.histogram(df, x= "Sex", title= "Sex Distribution & Heart Disease", color= "HeartDisease", barmode= "group")
fig.show()

In [48]:
fig = px.histogram(df, x= "ChestPainType", title= "Chest Pain Types", color= "HeartDisease", barmode= "group")
fig.show()

In [49]:
fig = px.histogram(df, x= "FastingBS", color= "HeartDisease", barmode= "group", title= "Fasting BP and Heart Disease")
fig.show()

In [50]:
fig = px.box(df, x= "HeartDisease", y= "Cholesterol", title= "Heart Disease & Cholesterol")
fig.show()

In [51]:
fig = px.violin(df, x= "HeartDisease", y= "Age", title= "Heart Disease & Age")
fig.show()

In [52]:
num_df = df.select_dtypes(include="number")
corr_matrix = num_df.corr()

fig = px.imshow(
    corr_matrix,
    text_auto=True,
    color_continuous_scale="RdBu",
    zmin=-1,
    zmax=1,
    title="Correlation Heatmap of Numerical Features"
)

fig.show()

#### Data Pre-processing

In [53]:
df_encode = pd.get_dummies(df)
df_encode = df_encode.astype(int)
df_encode.head()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_F,Sex_M,ChestPainType_ASY,...,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ExerciseAngina_N,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0,0,0,1,0,...,0,0,0,1,0,1,0,0,0,1
1,49,160,180,0,156,1,1,1,0,0,...,1,0,0,1,0,1,0,0,1,0
2,37,130,283,0,98,0,0,0,1,0,...,0,0,0,0,1,1,0,0,0,1
3,48,138,214,0,108,1,1,1,0,1,...,0,0,0,1,0,0,1,0,1,0
4,54,150,195,0,122,0,0,0,1,0,...,1,0,0,1,0,1,0,0,0,1

In [54]:
from scipy.stats import pearsonr

features = ["FastingBS", "Oldpeak", "Sex_F", "ChestPainType_ASY", "ChestPainType_ATA", "ChestPainType_NAP", "ChestPainType_TA", "ChestPainType_TA", "RestingECG_LVH", "RestingECG_Normal", "RestingECG_ST", "ExerciseAngina_N", "ExerciseAngina_Y",	"ST_Slope_Down", "ST_Slope_Flat", "ST_Slope_Up"]

correlation = {
    feature: pearsonr(df_encode[feature], df_encode["HeartDisease"])[0]
    for feature in features
}

correlation = pd.DataFrame(list(correlation.items()), columns= ["Features", "Correlation"])
correlation["abs_corr"] = correlation["Correlation"].abs()
correlation.sort_values(by= "abs_corr", ascending= False, inplace= True)
correlation.drop(axis= 1, columns= ["abs_corr"], inplace= True)
correlation.reset_index(inplace= True)
correlation.drop(axis= 1, columns= ["index"], inplace= True)

correlation

             Features  Correlation
0         ST_Slope_Up    -0.622164
1       ST_Slope_Flat     0.554134
2   ChestPainType_ASY     0.516716
3    ExerciseAngina_Y     0.494282
4    ExerciseAngina_N    -0.494282
5   ChestPainType_ATA    -0.401924
6             Oldpeak     0.392385
7               Sex_F    -0.305445
8           FastingBS     0.267291
9   ChestPainType_NAP    -0.212964
10      ST_Slope_Down     0.122527
11      RestingECG_ST     0.102527
12  RestingECG_Normal    -0.091580
13   ChestPainType_TA    -0.054790
14     RestingECG_LVH     0.010670

In [55]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

numeric_columns = ["Age", "RestingBP", "Cholesterol", "MaxHR", "Oldpeak"]

df_encode[numeric_columns] = scaler.fit_transform(df_encode[numeric_columns])
df_encode.head()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_F,Sex_M,ChestPainType_ASY,...,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ExerciseAngina_N,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,-1.433140,0.414825,0.831244,0,1.382928,-0.727592,0,0,1,0,...,0,0,0,1,0,1,0,0,0,1
1,-0.478484,1.527163,-1.214200,0,0.754157,0.282891,1,1,0,0,...,1,0,0,1,0,1,0,0,1,0
2,-1.751359,-0.141345,0.718651,0,-1.525138,-0.727592,0,0,1,0,...,0,0,0,0,1,1,0,0,0,1
3,-0.584556,0.303591,-0.576172,0,-1.132156,0.282891,1,1,0,1,...,0,0,0,1,0,0,1,0,1,0
4,0.051881,0.970994,-0.932717,0,-0.581981,-0.727592,0,0,1,0,...,1,0,0,1,0,1,0,0,0,1

#### Model Making

In [56]:
X = df_encode.drop(columns = ["HeartDisease"], axis= 1)
y = df_encode["HeartDisease"]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [57]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, f1_score, classification_report

models = {
    "Logistic Regression": LogisticRegression(),
    "KNN": KNeighborsClassifier(),
    "Naive Bayes": GaussianNB(),
    "Decision trees": DecisionTreeClassifier(),
    "SVM": SVC()
}

result = []

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    cr = classification_report(y_test, y_pred)
    result.append({
        "model": name,
        "accuracy": acc,
        "F1 score": f1
    })

result

[{'model': 'Logistic Regression',
  'accuracy': 0.8641304347826086,
  'F1 score': 0.8792270531400966},
 {'model': 'KNN',
  'accuracy': 0.8641304347826086,
  'F1 score': 0.8803827751196173},
 {'model': 'Naive Bayes',
  'accuracy': 0.842391304347826,
  'F1 score': 0.8557213930348259},
 {'model': 'Decision trees',
  'accuracy': 0.8152173913043478,
  'F1 score': 0.826530612244898},
 {'model': 'SVM',
  'accuracy': 0.8478260869565217,
  'F1 score': 0.8679245283018868}]

In [58]:
import joblib
joblib.dump(models["KNN"], "KNN_Heart.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(X.columns.tolist(), "columns.pkl")

['columns.pkl']